# Sync to OneDrive config file

# Follow the general format to specify directories that will be sync.
# Folders (or files) in the same directory must have the same indention.

# The highest level determines if the SRC and DEST directories will be mirrored or not.

# DEST will be the farthest right value, and will be relative to the "OneDrive_base" value.

OneDrive_base: C:\Users\wmsoc\OneDrive
NO_MIRROR:
    C:\Users\wmsoc\home:
        Documents:
            NCSU: Documents\NCSU
            Personal: Documents\Personal
            P.Projects: Documents\P.Projects
        Pictures:
            GrampasMedia: Pictures\GrampasMedia
            Saved Pictures: Pictures\Saved Pictures
            Wallpapers: Pictures\Wallpapers

MIRROR:
